-- init.sql
-- Table for storing raw log events from agents
CREATE TABLE IF NOT EXISTS logs (
    timestamp DateTime,
    hostname String,
    event_type String,
    user String,
    source_ip String,
    received_at DateTime DEFAULT now()
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (timestamp, hostname);

-- Table for storing alerts generated by the AI engine
CREATE TABLE IF NOT EXISTS alerts (
    alert_timestamp DateTime,
    event_timestamp DateTime,
    hostname String,
    user String,
    source_ip String,
    anomaly_score Float64,
    reason String,
    event_details String
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(alert_timestamp)
ORDER BY alert_timestamp;